version: "3.8"

services:
  app:
    container_name: simple-golang-tdd-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: always
